version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/
    networks:
      - go-book-net
    command: /bin/sh -c "go run main.go"
    stdin_open: true
    tty: true
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - .:/app:delegated,rw
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:9.6.2-alpine
    restart: always
    env_file:
      - .env
    expose:
      - "5432"
    ports:
      - 5432:5432
    networks:
      - go-book-net
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=postgres --list"
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  go-book-net: